DataProcessing.Core.Web/Controllers/BusinessToBusinessController.cs
using DataProcessing.Application.B2B.Command;
using DataProcessing.Application.B2B.Query;
using DataProcessing.Application.Common;
using DataProcessing.CommonModels;
using DataProcessing.Core.Web.Actions;
using DataProcessing.Core.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.IO;

namespace DataProcessing.Core.Web.Controllers
{
    [Authorize]
    public class BusinessToBusinessController : Controller
    {
        private readonly IOptions<DataProcessingSetting> _appSettings;
        private readonly IB2BSearchBlock _searchBlock;
        private readonly ISearchAction _searchAction;
        private readonly IGetSearchedFileStatuscs _getSearchedFileStatuscs;
        private readonly ISaveB2B _saveB2B;
        readonly ILogger<BusinessToBusinessController> _log;
        public BusinessToBusinessController(IOptions<DataProcessingSetting> appSettings,
            ISaveB2B saveB2B, IB2BSearchBlock searchBlock, ISearchAction searchAction,
            IGetSearchedFileStatuscs getSearchedFileStatuscs
            )
        {
            _appSettings = appSettings;
            _saveB2B = saveB2B;
            _searchBlock = searchBlock;
            _searchAction = searchAction;
            _getSearchedFileStatuscs = getSearchedFileStatuscs;
        }

        public IActionResult Index()
        {           
            return View(new B2BDashboard());
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View(new B2BUpload());
        }

        [HttpPost]
        public IActionResult Upload(IList<IFormFile> files)
        {
            CreateUploadFile createUploadFile = new CreateUploadFile();
            var fileCreation = createUploadFile.CreateAsync(files, _appSettings.Value.SharePath);
            fileCreation.Wait();
            var filePath = fileCreation.Result;
            var saveSummary = _saveB2B.Save(filePath);
            return View(new B2BUpload()
            {
                ErrorMessage = saveSummary.ErrorMessage,
                TotalCount = saveSummary.TotalCount,
                UploadCount = saveSummary.UploadCount
            });
        }

        public IActionResult Summary()
        {
            return View();
        }

        public IActionResult Search()
        {
            var searchFilterOption = _searchBlock.BindSearchBlock();
            return View(new B2BSearchModel() { SearchBlock = searchFilterOption });
        }

        [HttpPost]
        public IActionResult Search(SearchRequest searchRequest)
        {
            var searchSummary = _searchAction.Filter(new SearchFilter
            {
                Area = searchRequest.Area,
                BusinessCategoryId = searchRequest.BusinessCategoryId,
                Cities = searchRequest.Cities,
                Contries = searchRequest.Contries,
                Designation = searchRequest.Designation,
                States = searchRequest.States
            }, _appSettings.Value.SearchExport, _appSettings.Value.RowRange, _appSettings.Value.ZipFileRange);
            return Json(searchSummary);
        }

        public ActionResult DownLoadAsExcel(string searchId)
        {
            var fileName = $"{searchId}";
            var rootPath = _appSettings.Value.SearchExport;
            var filePath = $"{rootPath}{fileName}.xlsx";            
            var sampleTempate = new GetFileContent().GetFile(filePath);
            var templateName = "B2B";
            var fileType = Directory.Exists($"{rootPath}{fileName}") ? ".zip" : ".xlsx";
            return File(sampleTempate, "application/vnd.ms-excel", $"{templateName}{fileType}");
        }

        public ActionResult DownLoadAsCsv(string searchId)
        {
            var fileName = $"{searchId}";
            var rootPath = _appSettings.Value.SearchExport;
            var filePath = $"{rootPath}{fileName}.csv";
            var sampleTempate = new GetFileContent().GetFile(filePath);
            var templateName = "B2B";
            var fileType = Directory.Exists($"{rootPath}{fileName}") ? ".zip" : ".csv";
            return File(sampleTempate, "application/x-csv", $"{templateName}{fileType}");
        }

        public ActionResult CheckSearchFileAvailable(SearchRequestCheck searchRequestCheck)
        {
            var fileName = $"{searchRequestCheck.SearchId}";
            var rootPath = _appSettings.Value.SearchExport;
            var filePath = $"{rootPath}{fileName}.{ searchRequestCheck.Type} ";
            var fileType = GetFileType(searchRequestCheck.Type);
            var fileStatus = _getSearchedFileStatuscs.FileExist(searchRequestCheck.SearchId, fileType, filePath);
            return Json(fileStatus);
        }

        public ActionResult DownloadSampleTemplate(int sourceId)
        {            
            var sampleTempate = GetSampleFileContent.Get(_appSettings.Value.SampleDownloadPath, _appSettings.Value.Samples, sourceId);
            return File(sampleTempate.content, "application/vnd.ms-excel", $"{sampleTempate.FileName}.xlsx");
        }

        private int GetFileType(string fileType)
        {
            return (fileType.ToLower().Equals("xlsx") ? 0 : 1);
        }
    }
}

DataProcessing.Core.Web/Controllers/BusinessToCustomerController.cs
using DataProcessing.Application.B2C.Command;
using DataProcessing.Application.B2C.Query;
using DataProcessing.Application.Common;
using DataProcessing.CommonModels;
using DataProcessing.Core.Web.Actions;
using DataProcessing.Core.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.IO;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DataProcessing.Core.Web.Controllers
{
    [Authorize]
    public class BusinessToCustomerController : Controller
    {
        private readonly IOptions<DataProcessingSetting> _appSettings;
        private readonly ISaveB2C _saveB2C;
        private readonly IB2CSearchBlock _b2CSearchBlock;
        private readonly IB2CSearchAction _b2CSearchAction;
        private readonly IGetSearchedFileStatuscs _getSearchedFileStatuscs;
        public BusinessToCustomerController(IOptions<DataProcessingSetting> appSettings,
            ISaveB2C saveB2C,
         IB2CSearchBlock b2CSearchBlock, IB2CSearchAction b2CSearchAction, IGetSearchedFileStatuscs getSearchedFileStatuscs)
        {
            _appSettings = appSettings;
            _saveB2C = saveB2C;
            _b2CSearchBlock = b2CSearchBlock;
            _b2CSearchAction = b2CSearchAction;
            _getSearchedFileStatuscs = getSearchedFileStatuscs;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Upload(IList<IFormFile> files)
        {
            CreateUploadFile createUploadFile = new CreateUploadFile();
            var fileCreation = createUploadFile.CreateAsync(files, _appSettings.Value.SharePath);
            fileCreation.Wait();
            var filePath = fileCreation.Result;
            var saveSummary = _saveB2C.Save(filePath);
            return View(new UploadSummary()
            {
                ErrorMessage = saveSummary.ErrorMessage,
                TotalCount = saveSummary.TotalCount,
                UploadCount = saveSummary.UploadCount
            });
        }

        public IActionResult Summary()
        {
            return View();
        }

        public IActionResult Search()
        {
            var searchFilterOption = _b2CSearchBlock.BindSearchBlock();

            return View(searchFilterOption);
        }

        [HttpPost]
        public IActionResult Search(BusinessToCustomerSearchRequest searchRequest)
        {
            var searchSummary = _b2CSearchAction.Filter(new B2CSearchFilter
            {
                Area = searchRequest.Area,
                Cities = searchRequest.Cities,
                Contries = searchRequest.Contries,
                States = searchRequest.States,
                Age = searchRequest.Age,
                Experience = searchRequest.Experience,
                Roles = searchRequest.Roles,
                Salary = searchRequest.Salary
            }, _appSettings.Value.SearchExport, _appSettings.Value.RowRange, _appSettings.Value.ZipFileRange);
            return Json(searchSummary);
        }

        public ActionResult DownLoadAsExcel(string searchId)
        {
            var fileName = $"{searchId}";
            var rootPath = _appSettings.Value.SearchExport;
            var filePath = $"{rootPath}{fileName}.xlsx";
            var sampleTempate = new GetFileContent().GetFile(filePath);
            var templateName = "B2C";
            var fileType = Directory.Exists($"{rootPath}{fileName}") ? ".zip" : ".xlsx";
            return File(sampleTempate, "application/vnd.ms-excel", $"{templateName}{fileType}");
        }

        public ActionResult DownLoadAsCsv(string searchId)
        {
            var fileName = $"{searchId}";
            var rootPath = _appSettings.Value.SearchExport;
            var filePath = $"{rootPath}{fileName}.csv";
            var sampleTempate = new GetFileContent().GetFile(filePath);
            var templateName = "B2C";
            var fileType = Directory.Exists($"{rootPath}{fileName}") ? ".zip" : ".csv";
            return File(sampleTempate, "application/x-csv", $"{templateName}{fileType}");
        }

        public ActionResult CheckSearchFileAvailable(SearchRequestCheck searchRequestCheck)
        {
            var fileName = $"{searchRequestCheck.SearchId}";
            var rootPath = _appSettings.Value.SearchExport;
            var filePath = $"{rootPath}{fileName}.{ searchRequestCheck.Type} ";
            var fileType = GetFileType(searchRequestCheck.Type);
            var fileStatus = _getSearchedFileStatuscs.FileExist(searchRequestCheck.SearchId, fileType, filePath);
            return Json(fileStatus);
        }
        private int GetFileType(string fileType)
        {
            return (fileType.ToLower().Equals("xlsx") ? 0 : 1);
        }
    }
}

DataProcessing.Core.Web/Controllers/NumberLookupController.cs
using DataProcessing.Application.NumberLookup.Command;
using DataProcessing.Application.NumberLookup.Query;
using DataProcessing.Core.Web.Actions;
using DataProcessing.Core.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.Linq;

namespace DataProcessing.Core.Web.Controllers
{
    [Authorize]
    public class NumberLookupController : Controller
    {
        private readonly IOptions<DataProcessingSetting> _appSettings;
        private readonly ILoopupProcess _loopupProcess = null;
        private readonly IReadBulkNumberLookUp _readBulkNumberLookUp = null;
        private readonly IGetOperators _getOperators = null;
        private readonly IGetPhoneNetwork _getPhoneNetwork =  null;
        private readonly ISaveNumberLookUp _saveNumberLookUp = null;
        private readonly IGetNumberLookUpData _getNumberLookUpData = null;
        public NumberLookupController(IOptions<DataProcessingSetting> appSettings,
            ILoopupProcess loopupProcess,
            IReadBulkNumberLookUp readBulkNumberLookUp,
            IGetOperators operators,
            IGetPhoneNetwork getPhoneNetwork,
            ISaveNumberLookUp saveNumberLookUp,
            IGetNumberLookUpData getNumberLookUpData)
        {
            _appSettings = appSettings;
            _loopupProcess = loopupProcess;
            _readBulkNumberLookUp = readBulkNumberLookUp;
            _getOperators = operators;
            _getPhoneNetwork = getPhoneNetwork;
            _saveNumberLookUp = saveNumberLookUp;
            _getNumberLookUpData = getNumberLookUpData;
        }

        public IActionResult Index()
        {
            //var getOperators = _getOperators.Get();
            //List<Operator> operators = new List<Operator>();

            //foreach (var item in getOperators)
            //{
            //    operators.Add(new Operator { IsChecked = false, Text = item, Value = item });
            //}

            NumberLookUpDownload numberLookUpDownload = new NumberLookUpDownload()
            {
                //Operators = operators
            };
            return View(numberLookUpDownload);
        }

        public IActionResult AddLookup()
        {
            var seriesData = _getNumberLookUpData.GetNumberLookUp().Select(x => new NumberLookup { 
                Circle = x.Circle, 
                Operator = x.Operator, 
                Series = x.Phone,
                SeriesId = x.SeriesId
            });
            NumberLookup numberLookup = new NumberLookup() { AvilableSeries = seriesData };
            return View(numberLookup);
        }

        [HttpPost]
        public IActionResult SaveLookup(NumberLookup numberLookup)
        {
            numberLookup.IsUploaded = true;
            numberLookup.UploadMessage = "Succesfully uploaded";
            return View("AddLookup", numberLookup);
        }

        [HttpPost]
        public IActionResult BulkLookup(IList<IFormFile> files)
        {
            CreateUploadFile createUploadFile = new CreateUploadFile();
            var fileCreation = createUploadFile.CreateAsync(files, _appSettings.Value.SharePath);
            fileCreation.Wait();
            var filePath = fileCreation.Result;
            _readBulkNumberLookUp.Process(filePath);
            NumberLookup numberLookup = new NumberLookup() { IsUploaded = true, UploadMessage = "Succesfully uploaded" };
            return View("AddLookup", numberLookup);
        }

        [HttpPost]
        public IActionResult Index(IList<IFormFile> files, NumberLookUpDownload noLookUpDownload)
        {
            CreateUploadFile createUploadFile = new CreateUploadFile();
            var fileCreation = createUploadFile.CreateAsync(files, _appSettings.Value.SharePath);
            fileCreation.Wait();
            var filePath = fileCreation.Result;
            //var filters = noLookUpDownload.Operators.Where(x => x.IsChecked).Select(x=>x.Value);
            var searchResult = _loopupProcess.Process(filePath, _appSettings.Value.NumberLookup, noLookUpDownload.LookupNumbers);
            
            List<Operator> operators = new List<Operator>();
            foreach (var item in searchResult.Item1)
            {
                operators.Add(new Operator { IsChecked = false, Text = item, Value = item });
            }
            NumberLookUpDownload numberLookUpDownloadh = new NumberLookUpDownload()
            {
                Operators = operators,
                SearchId = searchResult.Item2
            };
            return View(numberLookUpDownloadh);

            /*var rootPath = _appSettings.Value.NumberLookup;
            var newfilePath = $"{rootPath}{fileName}.xlsx";
            var sampleTempate = new GetFileContent().GetFile(newfilePath);
            var templateName = "Number LookUp";
            return File(sampleTempate, "application/vnd.ms-excel", $"{templateName}.xlsx"); */
        }

        public ActionResult DownLoadNumberLookup(string fileName)
        {
            var rootPath = _appSettings.Value.NumberLookup;
            var filePath = $"{rootPath}{fileName}.xlsx";
            var sampleTempate = new GetFileContent().GetFile(filePath);
            var templateName = "Number LookUp";
            return File(sampleTempate, "application/vnd.ms-excel", $"{templateName}.xlsx");
        }

        [HttpPost]
        public ActionResult DownloadNetwork(NumberLookupFilter numberLookupFilter)
        {
            var numberLookups = _getPhoneNetwork.Get(numberLookupFilter.LookupId, numberLookupFilter.Networks);                        
            var rootPath = _appSettings.Value.NumberLookup;
            var fileName = _saveNumberLookUp.CreateAndSave(numberLookups, rootPath);
            return Json(new { fileName = fileName });
        }

        [HttpPost]
        public ActionResult DeleteOperator(string operatorId)
        {
            _readBulkNumberLookUp.Remove(operatorId);
            return Json("");
        }

        [HttpPost]
        public ActionResult UpdateOperator(string operatorId, Numbers numberLookup)
        {
            _readBulkNumberLookUp.Update(operatorId, numberLookup);
            return Json("");
        }

    }
}

DataProcessing.Core.Web/Views/Shared/_AuthendiactionLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/assets/plugins/morris.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/icons.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap-table.min.css" rel="stylesheet" />
    <script src="~/assets/js/modernizr.min.js"></script>
    <style type="text/css">
        #divLoading {
            margin: 0px;
            padding: 0px;
            position: fixed;
            right: 0px;
            top: 0px;
            width: 100%;
            height: 100%;
            background-color: rgb(102, 102, 102);
            z-index: 30001;
            opacity: 0.9;
            display: none;
        }
    </style>
</head>

<body>
    <div id="divLoading">
        <p style="position: absolute; color: White; top: 50%; left: 45%;">
            <img src="~/assets/images/loader4.gif" />
        </p>
    </div>
    <!-- Begin page -->
    <div id="wrapper">
        <div>

            <!-- content -->
            <div class="content">
                @RenderBody()
            </div>

            <!-- content -->
            <!-- footer -->
            <footer class="footer">
                <p>&copy; 2018 - DataProcessing.Core.Web</p>
            </footer>
        </div>

        <!-- ========== Right sidebar end ========== -->

    </div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/jquery.validate.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DataProcessing.Core.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataProcessing.Core.Web</title>
    <link href="~/assets/plugins/morris.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/icons.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap-table.min.css" rel="stylesheet" />
    <link href="~/assets/fonts/font-awesome.css" rel="stylesheet" />
    <script src="~/assets/js/modernizr.min.js"></script>
    <link href="~/assets/css/fSelect.css" rel="stylesheet" />
    <style type="text/css">
        #divLoading {
            margin: 0px;
            padding: 0px;
            position: fixed;
            right: 0px;
            top: 0px;
            width: 100%;
            height: 100%;
            background-color: rgb(102, 102, 102);
            z-index: 30001;
            opacity: 0.9;
            display: none;
        }
    </style>
</head>
<body>
    <div id="divLoading">
        <p style="position: absolute; color: White; top: 50%; left: 45%;">
            <img src="~/assets/images/loader4.gif" />
        </p>
    </div>
    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- LOGO -->
            <div class="topbar-left">
                <div class="text-center">
                    <a asp-controller="Home" asp-action="Index" class="logo">
                        <img src="~/assets/images/download.png" />
                        @*<i class="icon-magnet icon-c-logo"></i>
                            <span>Ub<i class="md md-album"></i>ld</span>*@
                    </a>
                    <!-- Image Logo here -->
                    <!--<a href="index.html" class="logo">-->
                    <!--<i class="icon-c-logo"> <img src="assets/images/logo_sm.png" height="42"/> </i>-->
                    <!--<span><img src="assets/images/logo_light.png" height="20"/></span>-->
                    <!--</a>-->
                </div>
            </div>

            <!-- Button mobile view to collapse sidebar menu -->
            <nav class="navbar-custom">

                <ul class="list-inline float-right mb-0">

                    <li class="list-inline-item dropdown notification-list">
                        <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <img src="~/assets/images/users/avatar-1.jpg" alt="user" class="rounded-circle">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h5 class="text-overflow"><small>Welcome ! John</small> </h5>
                            </div>
                            <!-- item-->
                            <a asp-controller="DataProcessAuthentication" asp-action="Logout" class="dropdown-item notify-item">
                                <i class="zmdi zmdi-power"></i>
                                <span>Logout</span>
                            </a>

                        </div>
                    </li>

                </ul>

                <ul class="list-inline menu-left mb-0">
                    <li class="float-left">
                        <button class="button-menu-mobile open-left waves-light waves-effect">
                            <i class="dripicons-menu"></i>
                        </button>
                    </li>

                </ul>

            </nav>

        </div>
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar start ========== -->

        <div class="left side-menu">
            <div class="sidebar-inner slimscrollleft">
                <!--- Divider -->
                <div id="sidebar-menu">
                    <ul>

                        <li class="text-muted menu-title">Navigation</li>

                        <li class="has_sub">
                            <a asp-controller="Home" asp-action="Index" class="waves-effect">
                                <i class="ti-home"></i>Home
                            </a>

                        </li>

                        <li class="has_sub">
                            <a href="javascript:void(0);" class="waves-effect">
                                <i class="icon-loop"></i> <span> B2B</span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="list-unstyled">
                                @*<li><a asp-controller="BusinessToBusiness" asp-action="Index">Dashboard</a></li>*@
                                <li><a asp-controller="BusinessToBusiness" asp-action="Upload"> <i class="ion-ios7-upload-outline"></i>Upload</a></li>
                                <li><a asp-controller="BusinessToBusiness" asp-action="Search"> <i class="ti-eye"></i>Search</a></li>
                                @*<li><a asp-controller="BusinessToBusiness" asp-action="Summary">Summary</a></li>*@
                            </ul>
                        </li>

                        <li class="has_sub">
                            <a href="javascript:void(0);" class="waves-effect">
                                <i class="icon-shuffle"></i> <span> B2C </span>
                                <span class="menu-arrow"></span>
                            </a>
                            </a>
                            <ul class="list-unstyled">
                                @*<li><a asp-controller="BusinessToCustomer" asp-action="Index">Dashboard</a></li>*@
                                <li><a asp-controller="BusinessToCustomer" asp-action="Upload"><i class="ion-ios7-upload-outline"></i>Upload</a></li>
                                <li><a asp-controller="BusinessToCustomer" asp-action="Search"><i class="ti-eye"></i>Search</a></li>
                                @*<li><a asp-controller="BusinessToCustomer" asp-action="Summary">Summary</a></li>*@
                            </ul>
                        </li>

                        <li class="has_sub">
                            <a href="javascript:void(0);" class="waves-effect">
                                <i class=" ti-reload"></i> <span> Customer Data </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="list-unstyled">
                                @*<li><a asp-controller="CustomerData" asp-action="Index">Dashboard</a></li>*@
                                <li><a asp-controller="CustomerData" asp-action="Upload"><i class="ion-ios7-upload-outline"></i>Upload</a></li>
                                <li><a asp-controller="CustomerData" asp-action="Search"><i class="ti-eye"></i>Search</a></li>
                                @*<li><a asp-controller="CustomerData" asp-action="Summary">Summary</a></li>*@

                            </ul>
                        </li>

                        <li class="has_sub">
                            <a href="javascript:void(0);" class="waves-effect">
                                <i class="ti-pencil-alt"></i><span> Number Lookup </span>
                                <span class="menu-arrow"></span>
                            </a>
                            <ul class="list-unstyled">
                                <li><a asp-controller="NumberLookup" asp-action="Index"><i class="ti-loop"></i>Lookup</a></li>
                                <li><a asp-controller="NumberLookup" asp-action="AddLookup"><i class=" typcn typcn-document-add"></i>Add Lookup</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- ========== Left Sidebar end ========== -->

        <div class="content-page">

            <!-- content -->
            <div class="content">
                @RenderBody()
            </div>

            <!-- content -->
            <!-- footer -->
            <footer class="footer">
                <p>&copy; 2018 - DataProcessing.Core.Web</p>
            </footer>
        </div>

        <!-- ========== main content end ========== -->
        <!-- ========== Right sidebar start ========== -->
        <div class="side-bar right-bar nicescroll">
            ...
        </div>

        <!-- ========== Right sidebar end ========== -->

    </div>

    <!-- jQuery  -->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/tether.min.js"></script><!-- Tether for Bootstrap -->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/detect.js"></script>
    <script src="~/assets/js/fastclick.js"></script>
    <script src="~/assets/js/jquery.slimscroll.js"></script>
    <script src="~/assets/js/jquery.blockUI.js"></script>
    <script src="~/assets/js/waves.js"></script>
    <script src="~/assets/js/wow.min.js"></script>
    <script src="~/assets/js/jquery.nicescroll.js"></script>
    <script src="~/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/assets/js/bootstrap-table.min.js"></script>
    @*<script src="assets/plugins/peity/jquery.peity.min.js"></script>*@

    <!-- jQuery  -->
    @*<script src="assets/plugins/waypoints/lib/jquery.waypoints.js"></script>
        <script src="assets/plugins/counterup/jquery.counterup.min.js"></script>

        <script src="assets/plugins/morris/morris.min.js"></script>
        <script src="assets/plugins/raphael/raphael-min.js"></script>

        <script src="assets/plugins/jquery-knob/jquery.knob.js"></script>

        <script src="assets/pages/jquery.dashboard.js"></script>*@
    <script src="~/assets/js/jquery.core.js"></script>
    <script src="~/assets/js/jquery.app.js"></script>
    <script src="~/assets/js/jquery.bs-table.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
